### ISSUE TITLE
lineage_report.csv can't be found. 

### ISSUE THREAD

**Issue by biocyberman** [hCoV-2019/pangolin#61] opened 2020-05-04 13:32 UTC
I am running with `pangolin` version 1.1.4. After several tries with specific tempdirs `--tempdir xxx` I still can't find `lineage_report.csv` output file under `outdir`. Can it be that `pangolin` remove output before it finishes (i.e. `clean up` the file from `tempdir` by mistake)? 

The jobs ends with messages look like the following:

```
[Mon May  4 15:32:30 2020]
Finished job 2.
1486 of 1488 steps (100%) done

[Mon May  4 15:32:30 2020]
rule add_failed_seqs:
    input: /user/pangtmp/tmpzs4hfj4m/lineage_report.pass_qc.csv, /user/pangtmp/tmpzs4hfj4m/query.failed_qc.fasta
    output: TestPang/lineage_report.csv
    jobid: 1

Job counts:
        count   jobs
        1       add_failed_seqs
        1
[Mon May  4 15:32:31 2020]
Finished job 1.
1487 of 1488 steps (100%) done

[Mon May  4 15:32:31 2020]
localrule all:
    input: TestPang/lineage_report.csv
    jobid: 0
```

**Comment by aineniamh** [comment] 2020-05-04 14:04
Hi, I've been trying to recreate this on my system and I can't seem to do that. I've tested with a combination of good and/or bad sequence examples and the final file gets created. 

What is the command you're running exactly and if you try running with `-o <output_directory>` does it still not work?  It shouldn't clean up the directory until `snakemake` creates the final target, which is the `lineage_report.csv`.

**Comment by biocyberman** [comment] 2020-05-04 14:15
This is command I ran for version 1.1.2 and I can find the output: `pangolin masked.fasta -o PangTest -t 50 --tempdir tmp`. So there is something on version `1.1.4`.

**Comment by biocyberman** [comment] 2020-05-04 14:30
This is the log of the failed version (1.1.4)
```
Removing temporary output file /user/pangtmp/tmpzs4hfj4m/tax71602366tax.txt.
Removing temporary output file /user/pangtmp/tmpzs4hfj4m/tax71602367tax.txt.
Removing temporary output file /user/pangtmp/tmpzs4hfj4m/tax71602368tax.txt.
Removing temporary output file /user/pangtmp/tmpzs4hfj4m/tax71602369tax.txt.
Removing temporary output file /user/pangtmp/tmpzs4hfj4m/tax71602370tax.txt.
Removing temporary output file /user/pangtmp/tmpzs4hfj4m/tax71602371tax.txt.
```

Probably `/user/pangtmp/tmpzs4hfj4m` is removed **before**  `/user/pangtmp/tmpzs4hfj4m/lineage_report.pass_qc.csv` is called in the next step. At  least I can't find `tmpzs4hfj4m` dir when the run finished neither. 


And the working version (1.1.2)

```
Removing temporary output file /user/Test0504/tmp/tax95872367tax.txt.
Removing temporary output file /user/Test0504/tmp/tax95872368tax.txt.
Removing temporary output file /user/Test0504/tmp/tax95872369tax.txt.
Removing temporary output file /user/Test0504/tmp/tax95872370tax.txt.
Removing temporary output file /user/Test0504/tmp/tax95872371tax.txt.
```

**Comment by aineniamh** [comment] 2020-05-04 14:43
So you're right the temp dir will be removed at the end, this is expected behaviour. Updates in this release now use `tempfile.TemporaryDirectory(suffix=None, prefix=None, dir=None)` as the default tempdir setup, or if you specify it. 

Those files you mention should get deleted after ``gather_reports`` is run and as you have `` /user/pangtmp/tmpzs4hfj4m/lineage_report.pass_qc.csv`` file as an input file for the following step I imagine that's what's happening. 

If you can post/attach the full output, that might help me figure out what's going on.

**Comment by aineniamh** [comment] 2020-05-04 16:06
I've just released [v1.1.5](https://github.com/hCoV-2019/pangolin/releases/tag/v1.1.5), with some updates and an unrelated bug fix. Maybe see if you can run `pangolin` using that. I've verified on three separate systems (two macosx and one linux) that the output file is produced as intended. 

If you could provide me with more information I may be able to help further.

**Comment by biocyberman** [comment] 2020-05-04 17:11
It's baffling then. I tried both on Linux and MacOS for version 1.1.5 and both didn't even create an output directory: 
```
cd pangolin/pangolin/test
pangolin test_seqs.fasta -o testout -t 4
```

On the Linux server I ran: 

`pangolin test.fasta --verbose -o tpan -t 50 --tempdir tmp &>pangolin_v1.1.5.log`

And the log file:
[pangolin_v1.1.5.log](https://github.com/hCoV-2019/pangolin/files/4576092/pangolin_v1.1.5.log)

No output created.

**Comment by jbv2** [comment] 2020-05-04 17:37
Hi!
I have the same issue, before I could ask pangolin the outdir I wanted.
Today I updated it because I wanted to see tree files from enhancement, I ran it with test data and outdir with csv file was just not created. Even if I ran it without specifying outdir, it should have created the file, but this is not happening.

**Comment by aineniamh** [comment] 2020-05-04 20:22
Okay, thanks @biocyberman for sending on the log files. I'll get to the bottom of this!

**Comment by aineniamh** [comment] 2020-05-04 20:50
Aha! I've found it. To fit in with #51 , I had updated the current working directory of pangolin to be the tempdir. I **think** the output file must have been written to the tempdir and then deleted afterwards. I've now updated the code and I think (🤞) it should be fixed now.

**Comment by aineniamh** [comment] 2020-05-04 20:57
https://github.com/hCoV-2019/pangolin/tree/v1.1.6 Here is a new release drafted with the fix. I'm going to close the issue now, but if there's still a problem and the file isn't being output still just let me know and I'll reopen it.

**Closed by aineniamh** 2020-05-04 20:57 UTC

**Comment by biocyberman** [comment] 2020-05-05 07:52
That fixed it, from my first test :)
